"""Regenerate docs/STRESS_TEST.md: does the analysis find true causes and avoid false ones?"""
from pathlib import Path
import sys

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "python"))
from cornhole_biomech import stress  # noqa: E402
from cornhole_biomech.performance import performance_summary  # noqa: E402
from cornhole_biomech.zones import ZoneSettings, zone_report  # noqa: E402

REPEATS = 200


def evaluate(athlete, n, seed=11):
    rng = np.random.default_rng(seed)
    claims, priority = {}, {}
    any_claim = 0
    for _ in range(REPEATS):
        rows = stress.simulate_session(athlete, n, rng)
        summary = performance_summary(rows, {})
        hits = {k for k, v in summary["variables"].items() if v["distinguishes"] or v["spread_distinguishes"]}
        any_claim += bool(hits)
        for k in hits:
            claims[k] = claims.get(k, 0) + 1
        top = (zone_report(rows, ZoneSettings()).get("priority") or {}).get("variable")
        if top:
            priority[top] = priority.get(top, 0) + 1
    short = lambda k: k.replace("bag_release_", "").replace("_m_s", "").replace("_deg", "").replace("_m", "")
    fmt = lambda d: ", ".join(f"{short(k)} {100 * v / REPEATS:.0f}%" for k, v in sorted(d.items(), key=lambda x: -x[1])) or "none"
    return 100 * any_claim / REPEATS, fmt(claims), fmt(priority)


def main():
    lines = ["# Stress test of the analysis", "",
             f"Generated by `scripts/stress_test.py` ({REPEATS} simulated sessions per cell). Each simulated athlete has a known",
             "cause of misses. Throws are generated with the drag-free first-contact model, a share of outcomes is randomized",
             "(bounce/slide/aim), and video-system measurement noise is added (speed 0.12 m/s, angle 1°, height 2 cm, 1 SD).",
             "", "| Athlete | Throws | Any outcome claim | Variables claimed (outcome comparison) | Largest spread ÷ window (zones) |",
             "|---|---|---|---|---|"]
    for athlete in stress.SCENARIOS:
        for n in (10, 20, 40):
            rate, claims, priority = evaluate(athlete, n)
            lines.append(f"| {athlete.name} | {n} | {rate:.0f}% | {claims} | {priority} |")
    lines += ["", "## Reading the table", "",
              "- **Outcome comparison** (scored vs missed, `performance.py`) makes a claim only with enough evidence. False claims stay",
              "  at or below about 5% for the null athlete and the pro whose misses come from bag behaviour, but real causes need",
              "  roughly 20–40 throws per athlete to be detected reliably. Record at least 20 throws, preferably 30–40.",
              "- **Physics priority** (`zones.py`) compares each release variable's spread with its green window. It names the",
              "  variable that truly drives misses even with 10 throws, because it does not need many misses. It is model-based:",
              "  treat it as the first hypothesis, and the outcome comparison as confirmation.",
              "- The last column always names the variable with the largest spread ÷ window ratio; the app turns it into advice",
              "  only when that spread actually exceeds the window. For the pro it does not, so no release cause is suggested.",
              "- The pro row is the \"small margins\" case: release spread fits inside the window, so the app says misses likely",
              "  come from aim or bag behaviour rather than inventing a body-mechanics cause.", ""]
    Path(__file__).resolve().parents[1].joinpath("docs/STRESS_TEST.md").write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
